version: '3.8'

services:
  
  mysql:
    image: mysql:8.0
    container_name: mysql_cash-flow
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: accountDB
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_cash_flow:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data_cash_flow: